version: '3.8'
services:
  mysql_db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql/volume:/var/lib/mysql
      - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - 9906:3306
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: Filip
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: uwbdb
    healthcheck:
      test: "exit 0"

  server:
    image: xmlynek/react-node-elearn-app
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=mysql://Filip:password@mysql_db/uwbdb
      - NODE_ENV=production
    depends_on:
      mysql_db:
        condition: service_healthy
    restart: always
    
  